/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CONTROLLER.CustomerPreparedStatement;
import MODEL.Customer;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TG
 */
public class CustomerInfo extends javax.swing.JFrame {

    /**
     * Creates new form StaffInfo
     */
    public CustomerInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CustomerIDTextField = new javax.swing.JTextField();
        CustomerNameTextField = new javax.swing.JTextField();
        CustomerPhoneNumberTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerInfo = new javax.swing.JTable();
        CustomerSearch = new javax.swing.JButton();
        CustomerCreate = new javax.swing.JButton();
        CustomerUpdate = new javax.swing.JButton();
        CustomerDelete = new javax.swing.JButton();
        Reload = new javax.swing.JButton();
        BackToHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jLabel3.setText("Phone Number");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Customer");

        CustomerInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Name", "Phone  Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CustomerInfo);

        CustomerSearch.setText("Search");
        CustomerSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerSearchActionPerformed(evt);
            }
        });

        CustomerCreate.setText("Create");
        CustomerCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerCreateActionPerformed(evt);
            }
        });

        CustomerUpdate.setText("Update");
        CustomerUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerUpdateActionPerformed(evt);
            }
        });

        CustomerDelete.setText("Delete");
        CustomerDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerDeleteActionPerformed(evt);
            }
        });

        Reload.setText("Reload");
        Reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadActionPerformed(evt);
            }
        });

        BackToHome.setText("Back to Home");
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CustomerSearch)
                        .addGap(18, 18, 18)
                        .addComponent(CustomerCreate)
                        .addGap(18, 18, 18)
                        .addComponent(CustomerUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(CustomerDelete)
                        .addGap(245, 245, 245)
                        .addComponent(Reload)
                        .addGap(18, 18, 18)
                        .addComponent(BackToHome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CustomerIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(CustomerNameTextField)
                                    .addComponent(CustomerPhoneNumberTextField))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CustomerIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CustomerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(CustomerPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerSearch)
                    .addComponent(CustomerCreate)
                    .addComponent(CustomerUpdate)
                    .addComponent(CustomerDelete)
                    .addComponent(Reload)
                    .addComponent(BackToHome))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CustomerInfo().setVisible(true);
    }//GEN-LAST:event_ReloadActionPerformed

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_BackToHomeActionPerformed

    private void CustomerSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerSearchActionPerformed
        // TODO add your handling code here:
        Customer cus = null;
        try {
            cus = CustomerPreparedStatement.Search(Integer.parseInt(CustomerIDTextField.getText()));
            if (cus == null) {
                JOptionPane.showMessageDialog(null, "No Customer with such ID!");
            } else {
                DefaultTableModel dtm = (DefaultTableModel) CustomerInfo.getModel();
                dtm.setRowCount(0);
                dtm.addRow(new Object[]{cus.getCustomerID(), cus.getName(), cus.getPhoneNumber()});
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_CustomerSearchActionPerformed

    private void CustomerCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerCreateActionPerformed
        // TODO add your handling code here:
        Customer cus = new Customer();
        try {
            cus.setCustomerID(Integer.parseInt(CustomerIDTextField.getText()));
            cus.setName(CustomerNameTextField.getText());
            cus.setPhoneNumber(CustomerPhoneNumberTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        CustomerPreparedStatement.Create(cus);
        
        setVisible(false);
        new CustomerInfo().setVisible(true);
    }//GEN-LAST:event_CustomerCreateActionPerformed

    private void CustomerUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerUpdateActionPerformed
        // TODO add your handling code here:
        Customer cus = new Customer();
        try {
            cus.setCustomerID(Integer.parseInt(CustomerIDTextField.getText()));
            cus.setName(CustomerNameTextField.getText());
            cus.setPhoneNumber(CustomerPhoneNumberTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        CustomerPreparedStatement.Update(cus);

        setVisible(false);
        new CustomerInfo().setVisible(true);
    }//GEN-LAST:event_CustomerUpdateActionPerformed

    private void CustomerDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerDeleteActionPerformed
        // TODO add your handling code here:
        String id = CustomerIDTextField.getText();
        int a = JOptionPane.showConfirmDialog(null, "Confirm Deletion", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            CustomerPreparedStatement.Delete(id);
            
            setVisible(false);
            new CustomerInfo().setVisible(true);
        }
    }//GEN-LAST:event_CustomerDeleteActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) CustomerInfo.getModel();
        ArrayList<Customer> list = CustomerPreparedStatement.Display();
        for (Customer p : list) {
            dm.addRow(new Object[]{p.getCustomerID(), p.getName(), p.getPhoneNumber()});
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHome;
    private javax.swing.JButton CustomerCreate;
    private javax.swing.JButton CustomerDelete;
    private javax.swing.JTextField CustomerIDTextField;
    private javax.swing.JTable CustomerInfo;
    private javax.swing.JTextField CustomerNameTextField;
    private javax.swing.JTextField CustomerPhoneNumberTextField;
    private javax.swing.JButton CustomerSearch;
    private javax.swing.JButton CustomerUpdate;
    private javax.swing.JButton Reload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
