/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MODEL.Pet;
import CONTROLLER.PetPreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TG
 */
public class PetInfo extends javax.swing.JFrame {

    /**
     * Creates new form ProductInfo
     */
    public PetInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PetIDTextField = new javax.swing.JTextField();
        PetNameTextField = new javax.swing.JTextField();
        PetBreedTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PetInfo = new javax.swing.JTable();
        PetSearch = new javax.swing.JButton();
        PetCreate = new javax.swing.JButton();
        PetUpdate = new javax.swing.JButton();
        PetDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PetAgeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PetPriceTextField = new javax.swing.JTextField();
        Reload = new javax.swing.JButton();
        BackToHome = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 111, -1, -1));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 142, -1, -1));

        jLabel3.setText("Breed");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 173, -1, -1));
        getContentPane().add(PetIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 109, 240, -1));
        getContentPane().add(PetNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 140, 240, -1));
        getContentPane().add(PetBreedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 171, 240, -1));

        PetInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PetID", "Name", "Breed", "Age", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(PetInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 109, -1, 268));

        PetSearch.setText("Search");
        PetSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetSearchActionPerformed(evt);
            }
        });
        getContentPane().add(PetSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 270, -1, -1));

        PetCreate.setText("Create");
        PetCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetCreateActionPerformed(evt);
            }
        });
        getContentPane().add(PetCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 270, -1, -1));

        PetUpdate.setText("Update");
        PetUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(PetUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 270, -1, -1));

        PetDelete.setText("Delete");
        PetDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(PetDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 313, -1, -1));

        jLabel4.setText("Age");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 204, -1, -1));
        getContentPane().add(PetAgeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 202, 240, -1));

        jLabel5.setText("Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 235, -1, -1));
        getContentPane().add(PetPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 233, 240, -1));

        Reload.setText("Reload");
        Reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadActionPerformed(evt);
            }
        });
        getContentPane().add(Reload, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 395, -1, -1));

        BackToHome.setText("Back to Home");
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });
        getContentPane().add(BackToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 395, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Pet");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 35, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pexels-photo-1108099.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-310, -60, 1130, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PetInfo().setVisible(true);
    }//GEN-LAST:event_ReloadActionPerformed

    private void PetSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetSearchActionPerformed
        // TODO add your handling code here:
        Pet p = null;
        try {
            p = PetPreparedStatement.Search(Integer.parseInt(PetIDTextField.getText()));
            if (p == null) {
                JOptionPane.showMessageDialog(null, "No pet with such ID!");
            } else {
                DefaultTableModel dtm = (DefaultTableModel) PetInfo.getModel();
                dtm.setRowCount(0);
                dtm.addRow(new Object[]{p.getPetID(), p.getName(), p.getBreed(), p.getAge(), p.getPrice()});
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_PetSearchActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) PetInfo.getModel();
        ArrayList<Pet> list = PetPreparedStatement.Display();
        for (Pet p : list) {
            dm.addRow(new Object[]{p.getPetID(), p.getName(), p.getBreed(), p.getAge(), p.getPrice()});
        }
    }//GEN-LAST:event_formComponentShown

    private void PetCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetCreateActionPerformed
        // TODO add your handling code here:
        Pet p = new Pet();
        try {
            p.setPetID(Integer.parseInt(PetIDTextField.getText()));
            p.setName(PetNameTextField.getText());
            p.setBreed(PetBreedTextField.getText());
            p.setAge(Integer.parseInt(PetAgeTextField.getText()));
            p.setPrice(Double.parseDouble(PetPriceTextField.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        PetPreparedStatement.Create(p);
        
        setVisible(false);
        new PetInfo().setVisible(true);
    }//GEN-LAST:event_PetCreateActionPerformed

    private void PetUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetUpdateActionPerformed
        // TODO add your handling code here:
        Pet p = new Pet();
        try {
            p.setPetID(Integer.parseInt(PetIDTextField.getText()));
            p.setName(PetNameTextField.getText());
            p.setBreed(PetBreedTextField.getText());
            p.setAge(Integer.parseInt(PetAgeTextField.getText()));
            p.setPrice(Double.parseDouble(PetPriceTextField.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        PetPreparedStatement.Update(p);

        setVisible(false);
        new PetInfo().setVisible(true);
    }//GEN-LAST:event_PetUpdateActionPerformed

    private void PetDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetDeleteActionPerformed
        // TODO add your handling code here:
        String id = PetIDTextField.getText();
        int a = JOptionPane.showConfirmDialog(null, "Confirm Deletion", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            PetPreparedStatement.Delete(id);
            
            setVisible(false);
            new PetInfo().setVisible(true);
        }
    }//GEN-LAST:event_PetDeleteActionPerformed

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_BackToHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHome;
    private javax.swing.JTextField PetAgeTextField;
    private javax.swing.JTextField PetBreedTextField;
    private javax.swing.JButton PetCreate;
    private javax.swing.JButton PetDelete;
    private javax.swing.JTextField PetIDTextField;
    private javax.swing.JTable PetInfo;
    private javax.swing.JTextField PetNameTextField;
    private javax.swing.JTextField PetPriceTextField;
    private javax.swing.JButton PetSearch;
    private javax.swing.JButton PetUpdate;
    private javax.swing.JButton Reload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
