/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MODEL.Pet;
import CONTROLLER.PetPreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TG
 */
public class PetInfo extends javax.swing.JFrame {

    /**
     * Creates new form ProductInfo
     */
    public PetInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PetIDTextField = new javax.swing.JTextField();
        PetNameTextField = new javax.swing.JTextField();
        PetBreedTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        PetInfo = new javax.swing.JTable();
        PetSearch = new javax.swing.JButton();
        PetCreate = new javax.swing.JButton();
        PetUpdate = new javax.swing.JButton();
        PetDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PetAgeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PetPriceTextField = new javax.swing.JTextField();
        PetReload = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jLabel3.setText("Breed");

        PetInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PetID", "Name", "Breed", "Age", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(PetInfo);

        PetSearch.setText("Search");
        PetSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetSearchActionPerformed(evt);
            }
        });

        PetCreate.setText("Create");
        PetCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetCreateActionPerformed(evt);
            }
        });

        PetUpdate.setText("Update");
        PetUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetUpdateActionPerformed(evt);
            }
        });

        PetDelete.setText("Delete");
        PetDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetDeleteActionPerformed(evt);
            }
        });

        jLabel4.setText("Age");

        jLabel5.setText("Price");

        PetReload.setText("Reload");
        PetReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PetReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel5))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PetIDTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(PetNameTextField)
                            .addComponent(PetBreedTextField)
                            .addComponent(PetAgeTextField)
                            .addComponent(PetPriceTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PetDelete)
                            .addComponent(PetSearch))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PetCreate)
                                .addGap(18, 18, 18)
                                .addComponent(PetUpdate))
                            .addComponent(PetReload))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(PetIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(PetNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PetBreedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PetAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(PetPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PetSearch)
                            .addComponent(PetCreate)
                            .addComponent(PetUpdate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PetDelete)
                            .addComponent(PetReload))))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PetReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetReloadActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new PetInfo().setVisible(true);
    }//GEN-LAST:event_PetReloadActionPerformed

    private void PetSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetSearchActionPerformed
        // TODO add your handling code here:
        Pet p = null;
        try {
            p = PetPreparedStatement.Search(Integer.parseInt(PetIDTextField.getText()));
            if (p == null) {
                JOptionPane.showMessageDialog(null, "No pet with such ID!");
            } else {
                DefaultTableModel dtm = (DefaultTableModel) PetInfo.getModel();
                dtm.setRowCount(0);
                dtm.addRow(new Object[]{p.getId(), p.getName(), p.getBreed(), p.getAge(), p.getPrice()});
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_PetSearchActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) PetInfo.getModel();
        ArrayList<Pet> list = PetPreparedStatement.Display();
        for (Pet p : list) {
            dm.addRow(new Object[]{p.getId(), p.getName(), p.getBreed(), p.getAge(), p.getPrice()});
        }
    }//GEN-LAST:event_formComponentShown

    private void PetCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetCreateActionPerformed
        // TODO add your handling code here:
        Pet p = new Pet();
        try {
            p.setId(Integer.parseInt(PetIDTextField.getText()));
            p.setName(PetNameTextField.getText());
            p.setBreed(PetBreedTextField.getText());
            p.setAge(Integer.parseInt(PetAgeTextField.getText()));
            p.setPrice(Double.parseDouble(PetPriceTextField.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        PetPreparedStatement.Create(p);
        
        setVisible(false);
        new PetInfo().setVisible(true);
    }//GEN-LAST:event_PetCreateActionPerformed

    private void PetUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetUpdateActionPerformed
        // TODO add your handling code here:
        Pet p = new Pet();
        try {
            p.setId(Integer.parseInt(PetIDTextField.getText()));
            p.setName(PetNameTextField.getText());
            p.setBreed(PetBreedTextField.getText());
            p.setAge(Integer.parseInt(PetAgeTextField.getText()));
            p.setPrice(Double.parseDouble(PetPriceTextField.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        PetPreparedStatement.Update(p);

        setVisible(false);
        new PetInfo().setVisible(true);
    }//GEN-LAST:event_PetUpdateActionPerformed

    private void PetDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PetDeleteActionPerformed
        // TODO add your handling code here:
        String id = PetIDTextField.getText();
        int a = JOptionPane.showConfirmDialog(null, "Confirm Deletion", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            PetPreparedStatement.Delete(id);
            
            setVisible(false);
            new PetInfo().setVisible(true);
        }
    }//GEN-LAST:event_PetDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PetAgeTextField;
    private javax.swing.JTextField PetBreedTextField;
    private javax.swing.JButton PetCreate;
    private javax.swing.JButton PetDelete;
    private javax.swing.JTextField PetIDTextField;
    private javax.swing.JTable PetInfo;
    private javax.swing.JTextField PetNameTextField;
    private javax.swing.JTextField PetPriceTextField;
    private javax.swing.JButton PetReload;
    private javax.swing.JButton PetSearch;
    private javax.swing.JButton PetUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
