/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MODEL.Product;
import CONTROLLER.ProductPreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author TG
 */
public class ProductInfo extends javax.swing.JFrame {

    /**
     * Creates new form ProductInfo
     */
    public ProductInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductID = new javax.swing.JLabel();
        ProductName = new javax.swing.JLabel();
        ProductPrice = new javax.swing.JLabel();
        ProductIDTextField = new javax.swing.JTextField();
        ProductNameTextField = new javax.swing.JTextField();
        ProductPriceTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductInfo = new javax.swing.JTable();
        ProductSearch = new javax.swing.JButton();
        ProductCreate = new javax.swing.JButton();
        ProductUpdate = new javax.swing.JButton();
        ProductDelete = new javax.swing.JButton();
        Reload = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        BillInfo = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        ProductCompute = new javax.swing.JButton();
        ProductQuantityTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BackToHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ProductID.setText("Product ID");
        getContentPane().add(ProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 97, -1, -1));

        ProductName.setText("Name");
        getContentPane().add(ProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 134, -1, -1));

        ProductPrice.setText("Price");
        getContentPane().add(ProductPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 171, -1, -1));
        getContentPane().add(ProductIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 95, 240, -1));
        getContentPane().add(ProductNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 132, 240, -1));
        getContentPane().add(ProductPriceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 169, 240, -1));

        ProductInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 132, 428, 160));

        ProductSearch.setText("Search");
        ProductSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductSearchActionPerformed(evt);
            }
        });
        getContentPane().add(ProductSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 206, -1, -1));

        ProductCreate.setText("Create");
        ProductCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductCreateActionPerformed(evt);
            }
        });
        getContentPane().add(ProductCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 206, -1, -1));

        ProductUpdate.setText("Update");
        ProductUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(ProductUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 206, -1, -1));

        ProductDelete.setText("Delete");
        ProductDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(ProductDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 249, -1, -1));

        Reload.setText("Reload");
        Reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadActionPerformed(evt);
            }
        });
        getContentPane().add(Reload, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 483, -1, -1));

        BillInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(BillInfo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 348, 428, 160));

        jTextField2.setText("Bill Info");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 310, -1, -1));

        ProductCompute.setText("Compute");
        ProductCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductComputeActionPerformed(evt);
            }
        });
        getContentPane().add(ProductCompute, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 348, -1, -1));
        getContentPane().add(ProductQuantityTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 310, 238, -1));

        jLabel1.setText("Quantity");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 312, -1, -1));

        BackToHome.setText("Back to Home");
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });
        getContentPane().add(BackToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 483, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Product");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 29, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pexels-photo-1957478.jpeg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) ProductInfo.getModel();
        ArrayList<Product> list = ProductPreparedStatement.Display();
        for (Product p : list) {
            dm.addRow(new Object[]{p.getProductID(), p.getName(), p.getPrice()});
        }
    }//GEN-LAST:event_formComponentShown

    private void ProductSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductSearchActionPerformed
        // TODO add your handling code here:
        Product p = null;
        p = ProductPreparedStatement.Search(ProductIDTextField.getText());
        if (p == null) {
                JOptionPane.showMessageDialog(null, "No product with such ID!");
        } else {
            DefaultTableModel dtm  =  (DefaultTableModel) ProductInfo.getModel();
            dtm.setRowCount(0);
            dtm.addRow(new Object[]{p.getProductID(),p.getName(),p.getPrice()});
        }
    }//GEN-LAST:event_ProductSearchActionPerformed

    private void ReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ProductInfo().setVisible(true);
    }//GEN-LAST:event_ReloadActionPerformed

    private void ProductCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductCreateActionPerformed
        // TODO add your handling code here:
        Product p = new Product();
        try {
            p.setProductID(Integer.parseInt(ProductIDTextField.getText()));
            p.setName(ProductNameTextField.getText());
            p.setPrice(Double.parseDouble(ProductPriceTextField.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        ProductPreparedStatement.Create(p);
        
        setVisible(false);
        new ProductInfo().setVisible(true);
    }//GEN-LAST:event_ProductCreateActionPerformed

    private void ProductUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductUpdateActionPerformed
        // TODO add your handling code here:
        Product p = new Product();
        try {
            p.setProductID(Integer.parseInt(ProductIDTextField.getText()));
            p.setName(ProductNameTextField.getText());
            p.setPrice(Double.parseDouble(ProductPriceTextField.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        ProductPreparedStatement.Update(p);

        setVisible(false);
        new ProductInfo().setVisible(true);
    }//GEN-LAST:event_ProductUpdateActionPerformed

    private void ProductDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductDeleteActionPerformed
        // TODO add your handling code here:
        String id = ProductIDTextField.getText();
        int a = JOptionPane.showConfirmDialog(null, "Confirm Deletion", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            ProductPreparedStatement.Delete(id);
            
            setVisible(false);
            new ProductInfo().setVisible(true);
        }
    }//GEN-LAST:event_ProductDeleteActionPerformed

    private void ProductInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductInfoMouseClicked
        // TODO add your handling code here:
        int index = ProductInfo.getSelectedRow();
        TableModel model = ProductInfo.getModel();
        String product_id = model.getValueAt(index, 0).toString();
        Product p = ProductPreparedStatement.Search(product_id);
        
        ProductIDTextField.setText(String.valueOf(p.getProductID()));
        ProductNameTextField.setText(p.getName());
        ProductPriceTextField.setText(String.valueOf(p.getPrice()));
    }//GEN-LAST:event_ProductInfoMouseClicked

    private void ProductComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductComputeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) BillInfo.getModel();
        dm.addRow(new Object[] {
            ProductNameTextField.getText(),
            ProductPriceTextField.getText(),
            ProductQuantityTextField.getText(),
            ProductPreparedStatement.Search(ProductIDTextField.getText()).getPrice() *
                (double)Integer.parseInt(ProductQuantityTextField.getText())
        });
        
    }//GEN-LAST:event_ProductComputeActionPerformed

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_BackToHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHome;
    private javax.swing.JTable BillInfo;
    private javax.swing.JButton ProductCompute;
    private javax.swing.JButton ProductCreate;
    private javax.swing.JButton ProductDelete;
    private javax.swing.JLabel ProductID;
    private javax.swing.JTextField ProductIDTextField;
    private javax.swing.JTable ProductInfo;
    private javax.swing.JLabel ProductName;
    private javax.swing.JTextField ProductNameTextField;
    private javax.swing.JLabel ProductPrice;
    private javax.swing.JTextField ProductPriceTextField;
    private javax.swing.JTextField ProductQuantityTextField;
    private javax.swing.JButton ProductSearch;
    private javax.swing.JButton ProductUpdate;
    private javax.swing.JButton Reload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
