/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import MODEL.Product;
import CONTROLLER.ProductPreparedStatement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author TG
 */
public class ProductInfo extends javax.swing.JFrame {

    /**
     * Creates new form ProductInfo
     */
    public ProductInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductID = new javax.swing.JLabel();
        ProductName = new javax.swing.JLabel();
        ProductPrice = new javax.swing.JLabel();
        ProductIDTextField = new javax.swing.JTextField();
        ProductNameTextField = new javax.swing.JTextField();
        ProductPriceTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProductInfo = new javax.swing.JTable();
        ProductSearch = new javax.swing.JButton();
        ProductCreate = new javax.swing.JButton();
        ProductUpdate = new javax.swing.JButton();
        ProductDelete = new javax.swing.JButton();
        Reload = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        BillInfo = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        ProductCompute = new javax.swing.JButton();
        ProductQuantityTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BackToHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        ProductID.setText("Product ID");

        ProductName.setText("Name");

        ProductPrice.setText("Price");

        ProductInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Name", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductInfoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductInfo);

        ProductSearch.setText("Search");
        ProductSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductSearchActionPerformed(evt);
            }
        });

        ProductCreate.setText("Create");
        ProductCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductCreateActionPerformed(evt);
            }
        });

        ProductUpdate.setText("Update");
        ProductUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductUpdateActionPerformed(evt);
            }
        });

        ProductDelete.setText("Delete");
        ProductDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductDeleteActionPerformed(evt);
            }
        });

        Reload.setText("Reload");
        Reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadActionPerformed(evt);
            }
        });

        jTextField1.setText("Product Info");

        BillInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Price", "Quantity", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(BillInfo);

        jTextField2.setText("Bill Info");

        ProductCompute.setText("Compute");
        ProductCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductComputeActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantity");

        BackToHome.setText("Back to Home");
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Product");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ProductID)
                                            .addComponent(ProductName)
                                            .addComponent(ProductPrice))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ProductIDTextField)
                                            .addComponent(ProductNameTextField)
                                            .addComponent(ProductPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(ProductSearch)
                                                .addGap(18, 18, 18)
                                                .addComponent(ProductCreate))
                                            .addComponent(ProductDelete))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ProductUpdate)
                                            .addComponent(ProductCompute))))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Reload)
                                        .addGap(18, 18, 18)
                                        .addComponent(BackToHome))
                                    .addComponent(ProductQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Reload)
                        .addComponent(BackToHome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ProductID)
                            .addComponent(ProductIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ProductName)
                                    .addComponent(ProductNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ProductPrice)
                                    .addComponent(ProductPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ProductSearch)
                                    .addComponent(ProductCreate)
                                    .addComponent(ProductUpdate))
                                .addGap(18, 18, 18)
                                .addComponent(ProductDelete))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductCompute))))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) ProductInfo.getModel();
        ArrayList<Product> list = ProductPreparedStatement.Display();
        for (Product p : list) {
            dm.addRow(new Object[]{p.getProductID(), p.getName(), p.getPrice()});
        }
    }//GEN-LAST:event_formComponentShown

    private void ProductSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductSearchActionPerformed
        // TODO add your handling code here:
        Product p = null;
        p = ProductPreparedStatement.Search(ProductIDTextField.getText());
        if (p == null) {
                JOptionPane.showMessageDialog(null, "No product with such ID!");
        } else {
            DefaultTableModel dtm  =  (DefaultTableModel) ProductInfo.getModel();
            dtm.setRowCount(0);
            dtm.addRow(new Object[]{p.getProductID(),p.getName(),p.getPrice()});
        }
    }//GEN-LAST:event_ProductSearchActionPerformed

    private void ReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ProductInfo().setVisible(true);
    }//GEN-LAST:event_ReloadActionPerformed

    private void ProductCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductCreateActionPerformed
        // TODO add your handling code here:
        Product p = new Product();
        try {
            p.setProductID(Integer.parseInt(ProductIDTextField.getText()));
            p.setName(ProductNameTextField.getText());
            p.setPrice(Double.parseDouble(ProductPriceTextField.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        ProductPreparedStatement.Create(p);
        
        setVisible(false);
        new ProductInfo().setVisible(true);
    }//GEN-LAST:event_ProductCreateActionPerformed

    private void ProductUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductUpdateActionPerformed
        // TODO add your handling code here:
        Product p = new Product();
        try {
            p.setProductID(Integer.parseInt(ProductIDTextField.getText()));
            p.setName(ProductNameTextField.getText());
            p.setPrice(Double.parseDouble(ProductPriceTextField.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        ProductPreparedStatement.Update(p);

        setVisible(false);
        new ProductInfo().setVisible(true);
    }//GEN-LAST:event_ProductUpdateActionPerformed

    private void ProductDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductDeleteActionPerformed
        // TODO add your handling code here:
        String id = ProductIDTextField.getText();
        int a = JOptionPane.showConfirmDialog(null, "Confirm Deletion", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            ProductPreparedStatement.Delete(id);
            
            setVisible(false);
            new ProductInfo().setVisible(true);
        }
    }//GEN-LAST:event_ProductDeleteActionPerformed

    private void ProductInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductInfoMouseClicked
        // TODO add your handling code here:
        int index = ProductInfo.getSelectedRow();
        TableModel model = ProductInfo.getModel();
        String product_id = model.getValueAt(index, 0).toString();
        Product p = ProductPreparedStatement.Search(product_id);
        
        ProductIDTextField.setText(String.valueOf(p.getProductID()));
        ProductNameTextField.setText(p.getName());
        ProductPriceTextField.setText(String.valueOf(p.getPrice()));
    }//GEN-LAST:event_ProductInfoMouseClicked

    private void ProductComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductComputeActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) BillInfo.getModel();
        dm.addRow(new Object[] {
            ProductNameTextField.getText(),
            ProductPriceTextField.getText(),
            ProductQuantityTextField.getText(),
            ProductPreparedStatement.Search(ProductIDTextField.getText()).getPrice() *
                (double)Integer.parseInt(ProductQuantityTextField.getText())
        });
        
    }//GEN-LAST:event_ProductComputeActionPerformed

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_BackToHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHome;
    private javax.swing.JTable BillInfo;
    private javax.swing.JButton ProductCompute;
    private javax.swing.JButton ProductCreate;
    private javax.swing.JButton ProductDelete;
    private javax.swing.JLabel ProductID;
    private javax.swing.JTextField ProductIDTextField;
    private javax.swing.JTable ProductInfo;
    private javax.swing.JLabel ProductName;
    private javax.swing.JTextField ProductNameTextField;
    private javax.swing.JLabel ProductPrice;
    private javax.swing.JTextField ProductPriceTextField;
    private javax.swing.JTextField ProductQuantityTextField;
    private javax.swing.JButton ProductSearch;
    private javax.swing.JButton ProductUpdate;
    private javax.swing.JButton Reload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
