/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CONTROLLER.StaffPreparedStatement;
import MODEL.Staff;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TG
 */
public class StaffInfo extends javax.swing.JFrame {

    /**
     * Creates new form StaffInfo
     */
    public StaffInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StaffIDTextField = new javax.swing.JTextField();
        StaffNameTextField = new javax.swing.JTextField();
        StaffPhoneNumberTextField = new javax.swing.JTextField();
        StaffEmailTextField = new javax.swing.JTextField();
        StaffPasswordTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StaffInfo = new javax.swing.JTable();
        StaffSearch = new javax.swing.JButton();
        StaffCreate = new javax.swing.JButton();
        StaffUpdate = new javax.swing.JButton();
        StaffDelete = new javax.swing.JButton();
        Reload = new javax.swing.JButton();
        BackToHome = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 121, -1, -1));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 158, -1, -1));

        jLabel3.setText("Phone Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 195, -1, -1));

        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 232, -1, -1));

        jLabel5.setText("Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 269, -1, -1));
        getContentPane().add(StaffIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 119, 219, -1));
        getContentPane().add(StaffNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 156, 219, -1));
        getContentPane().add(StaffPhoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 193, 219, -1));
        getContentPane().add(StaffEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 230, 219, -1));
        getContentPane().add(StaffPasswordTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 267, 219, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Staff");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 30, -1, -1));

        StaffInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Name", "Phone  Number", "Email", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(StaffInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 84, -1, 202));

        StaffSearch.setText("Search");
        StaffSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffSearchActionPerformed(evt);
            }
        });
        getContentPane().add(StaffSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 304, -1, -1));

        StaffCreate.setText("Create");
        StaffCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffCreateActionPerformed(evt);
            }
        });
        getContentPane().add(StaffCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 304, -1, -1));

        StaffUpdate.setText("Update");
        StaffUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(StaffUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 304, -1, -1));

        StaffDelete.setText("Delete");
        StaffDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(StaffDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 304, -1, -1));

        Reload.setText("Reload");
        Reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadActionPerformed(evt);
            }
        });
        getContentPane().add(Reload, new org.netbeans.lib.awtextra.AbsoluteConstraints(651, 304, -1, -1));

        BackToHome.setText("Back to Home");
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });
        getContentPane().add(BackToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(739, 304, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pexels-photo-1957478.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new StaffInfo().setVisible(true);
    }//GEN-LAST:event_ReloadActionPerformed

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_BackToHomeActionPerformed

    private void StaffSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffSearchActionPerformed
        // TODO add your handling code here:
        Staff p = null;
        try {
            p = StaffPreparedStatement.Search(Integer.parseInt(StaffIDTextField.getText()));
            if (p == null) {
                JOptionPane.showMessageDialog(null, "No Staff with such ID!");
            } else {
                DefaultTableModel dtm = (DefaultTableModel) StaffInfo.getModel();
                dtm.setRowCount(0);
                dtm.addRow(new Object[]{p.getStaffID(), p.getName(), p.getPhoneNumber(), p.getEmail(), p.getPassword()});
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_StaffSearchActionPerformed

    private void StaffCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffCreateActionPerformed
        // TODO add your handling code here:
        Staff staff = new Staff();
        try {
            staff.setStaffID(Integer.parseInt(StaffIDTextField.getText()));
            staff.setName(StaffNameTextField.getText());
            staff.setPhoneNumber(StaffPhoneNumberTextField.getText());
            staff.setEmail(StaffEmailTextField.getText());
            staff.setPassword(StaffPasswordTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        StaffPreparedStatement.Create(staff);
        
        setVisible(false);
        new StaffInfo().setVisible(true);
    }//GEN-LAST:event_StaffCreateActionPerformed

    private void StaffUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffUpdateActionPerformed
        // TODO add your handling code here:
        Staff staff = new Staff();
        try {
            staff.setStaffID(Integer.parseInt(StaffIDTextField.getText()));
            staff.setName(StaffNameTextField.getText());
            staff.setPhoneNumber(StaffPhoneNumberTextField.getText());
            staff.setEmail(StaffEmailTextField.getText());
            staff.setPassword(StaffPasswordTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        StaffPreparedStatement.Update(staff);

        setVisible(false);
        new StaffInfo().setVisible(true);
    }//GEN-LAST:event_StaffUpdateActionPerformed

    private void StaffDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffDeleteActionPerformed
        // TODO add your handling code here:
        String id = StaffIDTextField.getText();
        int a = JOptionPane.showConfirmDialog(null, "Confirm Deletion", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            StaffPreparedStatement.Delete(id);
            
            setVisible(false);
            new StaffInfo().setVisible(true);
        }
    }//GEN-LAST:event_StaffDeleteActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) StaffInfo.getModel();
        ArrayList<Staff> list = StaffPreparedStatement.Display();
        for (Staff p : list) {
            dm.addRow(new Object[]{p.getStaffID(), p.getName(), p.getPhoneNumber(), p.getEmail(), p.getPassword()});
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHome;
    private javax.swing.JButton Reload;
    private javax.swing.JButton StaffCreate;
    private javax.swing.JButton StaffDelete;
    private javax.swing.JTextField StaffEmailTextField;
    private javax.swing.JTextField StaffIDTextField;
    private javax.swing.JTable StaffInfo;
    private javax.swing.JTextField StaffNameTextField;
    private javax.swing.JTextField StaffPasswordTextField;
    private javax.swing.JTextField StaffPhoneNumberTextField;
    private javax.swing.JButton StaffSearch;
    private javax.swing.JButton StaffUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
