/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import CONTROLLER.StaffPreparedStatement;
import MODEL.Staff;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TG
 */
public class StaffInfo extends javax.swing.JFrame {

    /**
     * Creates new form StaffInfo
     */
    public StaffInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        StaffIDTextField = new javax.swing.JTextField();
        StaffNameTextField = new javax.swing.JTextField();
        StaffPhoneNumberTextField = new javax.swing.JTextField();
        StaffEmailTextField = new javax.swing.JTextField();
        StaffPasswordTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StaffInfo = new javax.swing.JTable();
        StaffSearch = new javax.swing.JButton();
        StaffCreate = new javax.swing.JButton();
        StaffUpdate = new javax.swing.JButton();
        StaffDelete = new javax.swing.JButton();
        Reload = new javax.swing.JButton();
        BackToHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jLabel3.setText("Phone Number");

        jLabel4.setText("Email");

        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setText("Staff");

        StaffInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Name", "Phone  Number", "Email", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(StaffInfo);

        StaffSearch.setText("Search");
        StaffSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffSearchActionPerformed(evt);
            }
        });

        StaffCreate.setText("Create");
        StaffCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffCreateActionPerformed(evt);
            }
        });

        StaffUpdate.setText("Update");
        StaffUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffUpdateActionPerformed(evt);
            }
        });

        StaffDelete.setText("Delete");
        StaffDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffDeleteActionPerformed(evt);
            }
        });

        Reload.setText("Reload");
        Reload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReloadActionPerformed(evt);
            }
        });

        BackToHome.setText("Back to Home");
        BackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(StaffSearch)
                            .addGap(18, 18, 18)
                            .addComponent(StaffCreate)
                            .addGap(18, 18, 18)
                            .addComponent(StaffUpdate)
                            .addGap(18, 18, 18)
                            .addComponent(StaffDelete)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Reload)
                            .addGap(18, 18, 18)
                            .addComponent(BackToHome))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(StaffIDTextField)
                                .addComponent(StaffNameTextField)
                                .addComponent(StaffPhoneNumberTextField)
                                .addComponent(StaffEmailTextField)
                                .addComponent(StaffPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(StaffIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(StaffNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(StaffPhoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(StaffEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(StaffPasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffSearch)
                    .addComponent(StaffCreate)
                    .addComponent(StaffUpdate)
                    .addComponent(StaffDelete)
                    .addComponent(Reload)
                    .addComponent(BackToHome))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReloadActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new StaffInfo().setVisible(true);
    }//GEN-LAST:event_ReloadActionPerformed

    private void BackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToHomeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Home().setVisible(true);
    }//GEN-LAST:event_BackToHomeActionPerformed

    private void StaffSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffSearchActionPerformed
        // TODO add your handling code here:
        Staff p = null;
        try {
            p = StaffPreparedStatement.Search(Integer.parseInt(StaffIDTextField.getText()));
            if (p == null) {
                JOptionPane.showMessageDialog(null, "No Staff with such ID!");
            } else {
                DefaultTableModel dtm = (DefaultTableModel) StaffInfo.getModel();
                dtm.setRowCount(0);
                dtm.addRow(new Object[]{p.getStaffID(), p.getName(), p.getPhoneNumber(), p.getEmail(), p.getPassword()});
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_StaffSearchActionPerformed

    private void StaffCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffCreateActionPerformed
        // TODO add your handling code here:
        Staff staff = new Staff();
        try {
            staff.setStaffID(Integer.parseInt(StaffIDTextField.getText()));
            staff.setName(StaffNameTextField.getText());
            staff.setPhoneNumber(StaffPhoneNumberTextField.getText());
            staff.setEmail(StaffEmailTextField.getText());
            staff.setPassword(StaffPasswordTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        StaffPreparedStatement.Create(staff);
        
        setVisible(false);
        new StaffInfo().setVisible(true);
    }//GEN-LAST:event_StaffCreateActionPerformed

    private void StaffUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffUpdateActionPerformed
        // TODO add your handling code here:
        Staff staff = new Staff();
        try {
            staff.setStaffID(Integer.parseInt(StaffIDTextField.getText()));
            staff.setName(StaffNameTextField.getText());
            staff.setPhoneNumber(StaffPhoneNumberTextField.getText());
            staff.setEmail(StaffEmailTextField.getText());
            staff.setPassword(StaffPasswordTextField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        StaffPreparedStatement.Update(staff);

        setVisible(false);
        new StaffInfo().setVisible(true);
    }//GEN-LAST:event_StaffUpdateActionPerformed

    private void StaffDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffDeleteActionPerformed
        // TODO add your handling code here:
        String id = StaffIDTextField.getText();
        int a = JOptionPane.showConfirmDialog(null, "Confirm Deletion", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            StaffPreparedStatement.Delete(id);
            
            setVisible(false);
            new StaffInfo().setVisible(true);
        }
    }//GEN-LAST:event_StaffDeleteActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel dm = (DefaultTableModel) StaffInfo.getModel();
        ArrayList<Staff> list = StaffPreparedStatement.Display();
        for (Staff p : list) {
            dm.addRow(new Object[]{p.getStaffID(), p.getName(), p.getPhoneNumber(), p.getEmail(), p.getPassword()});
        }
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToHome;
    private javax.swing.JButton Reload;
    private javax.swing.JButton StaffCreate;
    private javax.swing.JButton StaffDelete;
    private javax.swing.JTextField StaffEmailTextField;
    private javax.swing.JTextField StaffIDTextField;
    private javax.swing.JTable StaffInfo;
    private javax.swing.JTextField StaffNameTextField;
    private javax.swing.JTextField StaffPasswordTextField;
    private javax.swing.JTextField StaffPhoneNumberTextField;
    private javax.swing.JButton StaffSearch;
    private javax.swing.JButton StaffUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
